services:
  minio:
    image: minio/minio:latest
    container_name: snapmap-minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # консоль управления
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc:latest
    container_name: snapmap-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${S3_ACCESS_KEY:-minioadmin} ${S3_SECRET_KEY:-minioadmin} &&
      mc mb -p local/${S3_BUCKET:-snapmap} || true &&
      mc anonymous set download local/${S3_BUCKET:-snapmap} || true &&
      echo 'MinIO initialized'
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: snapmap-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  minio_data:
    driver: local
